# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'giaodien_design_last.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(821, 579)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.main_widget = QtWidgets.QStackedWidget(self.centralwidget)
        self.main_widget.setGeometry(QtCore.QRect(0, 0, 821, 541))
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        font.setPointSize(22)
        self.main_widget.setFont(font)
        self.main_widget.setStyleSheet("background-color:rgb(0, 0, 0);")
        self.main_widget.setObjectName("main_widget")
        self.display_menu = QtWidgets.QWidget()
        self.display_menu.setObjectName("display_menu")
        self.btn_menu_detec = QtWidgets.QPushButton(self.display_menu)
        self.btn_menu_detec.setGeometry(QtCore.QRect(170, 110, 481, 121))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(41)
        font.setBold(True)
        font.setWeight(75)
        self.btn_menu_detec.setFont(font)
        self.btn_menu_detec.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_menu_detec.setStyleSheet("QPushButton#btn_menu_detec{\n"
"border-radius: 15px;\n"
"background-color: rgba(255, 0, 0, 200);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#btn_menu_detec:hover{\n"
"border-radius: 15px;\n"
"background-color: rgba(255, 0, 0, 150);\n"
"color: rgb(255, 255, 255);\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Image/camera_xoaphong.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_menu_detec.setIcon(icon)
        self.btn_menu_detec.setIconSize(QtCore.QSize(60, 60))
        self.btn_menu_detec.setObjectName("btn_menu_detec")
        self.btn_menu_attendance = QtWidgets.QPushButton(self.display_menu)
        self.btn_menu_attendance.setGeometry(QtCore.QRect(170, 250, 481, 121))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(41)
        font.setBold(True)
        font.setWeight(75)
        self.btn_menu_attendance.setFont(font)
        self.btn_menu_attendance.setStyleSheet("QPushButton#btn_menu_attendance{\n"
"border-radius: 15px;\n"
"background-color: rgb(242, 115, 230,200);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#btn_menu_attendance:hover{\n"
"border-radius: 15px;\n"
"background-color: rgb(242, 115, 230,150);\n"
"color: rgb(255, 255, 255);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Image/danh_sach.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_menu_attendance.setIcon(icon1)
        self.btn_menu_attendance.setIconSize(QtCore.QSize(60, 60))
        self.btn_menu_attendance.setObjectName("btn_menu_attendance")
        self.btn_menu_close = QtWidgets.QPushButton(self.display_menu)
        self.btn_menu_close.setGeometry(QtCore.QRect(170, 390, 481, 121))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(41)
        font.setBold(True)
        font.setWeight(75)
        self.btn_menu_close.setFont(font)
        self.btn_menu_close.setStyleSheet("QPushButton#btn_menu_close{\n"
"border-radius: 15px;\n"
"background-color: rgb(28, 49, 94,200);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#btn_menu_close:hover{\n"
"border-radius: 15px;\n"
"background-color: rgb(28, 49, 94,150);\n"
"color: rgb(255, 255, 255);\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Image/close_rm.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_menu_close.setIcon(icon2)
        self.btn_menu_close.setIconSize(QtCore.QSize(60, 60))
        self.btn_menu_close.setObjectName("btn_menu_close")
        self.label = QtWidgets.QLabel(self.display_menu)
        self.label.setGeometry(QtCore.QRect(80, 10, 661, 81))
        font = QtGui.QFont()
        font.setFamily("MS Reference Specialty")
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: qradialgradient(stop:0.44 rgba(252, 128, 128, 80), stop:1 rgba(255, 255, 255, 0));")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Image/Menu.png"))
        self.label.setObjectName("label")
        self.main_widget.addWidget(self.display_menu)
        self.display_detec = QtWidgets.QWidget()
        self.display_detec.setObjectName("display_detec")
        self.tilte_detec = QtWidgets.QLabel(self.display_detec)
        self.tilte_detec.setGeometry(QtCore.QRect(210, 10, 471, 61))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(33)
        self.tilte_detec.setFont(font)
        self.tilte_detec.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:qradialgradient(stop:1 rgba(255, 255, 255, 0));\n"
"text-shadow: 6px 6px 0px rgba(0,0,0,0.2);\n"
"")
        self.tilte_detec.setText("")
        self.tilte_detec.setPixmap(QtGui.QPixmap("Image/Giam_sat.png"))
        self.tilte_detec.setScaledContents(False)
        self.tilte_detec.setAlignment(QtCore.Qt.AlignCenter)
        self.tilte_detec.setObjectName("tilte_detec")
        self.screen_detec_camera = QtWidgets.QLabel(self.display_detec)
        self.screen_detec_camera.setGeometry(QtCore.QRect(20, 90, 421, 331))
        self.screen_detec_camera.setStyleSheet("background-color: rgb(67, 66, 66);")
        self.screen_detec_camera.setFrameShape(QtWidgets.QFrame.Box)
        self.screen_detec_camera.setText("")
        self.screen_detec_camera.setObjectName("screen_detec_camera")
        self.input_detec_name = QtWidgets.QLineEdit(self.display_detec)
        self.input_detec_name.setGeometry(QtCore.QRect(460, 150, 311, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.input_detec_name.setFont(font)
        self.input_detec_name.setStyleSheet("border:none;\n"
"border-bottom: 3px solid rgba(255, 0, 0, 200); \n"
"background-color:qradialgradient(stop:1 rgba(255, 255, 255, 0));\n"
"color:rgb(255, 255, 255);\n"
"")
        self.input_detec_name.setObjectName("input_detec_name")
        self.input_detec_sbd = QtWidgets.QLineEdit(self.display_detec)
        self.input_detec_sbd.setGeometry(QtCore.QRect(460, 210, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.input_detec_sbd.setFont(font)
        self.input_detec_sbd.setStyleSheet("border:none;\n"
"border-bottom: 3px solid rgba(255, 0, 0, 200); \n"
"background-color:qradialgradient(stop:1 rgba(255, 255, 255, 0));\n"
"color:rgb(255, 255, 255);\n"
"\n"
"")
        self.input_detec_sbd.setObjectName("input_detec_sbd")
        self.input_detec_school = QtWidgets.QLineEdit(self.display_detec)
        self.input_detec_school.setGeometry(QtCore.QRect(460, 260, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.input_detec_school.setFont(font)
        self.input_detec_school.setStyleSheet("border:none;\n"
"border-bottom: 3px solid rgba(255, 0, 0, 200); \n"
"background-color:qradialgradient(stop:1 rgba(255, 255, 255, 0));\n"
"color:rgb(255, 255, 255);\n"
"\n"
"")
        self.input_detec_school.setObjectName("input_detec_school")
        self.input_detec_class = QtWidgets.QLineEdit(self.display_detec)
        self.input_detec_class.setGeometry(QtCore.QRect(460, 320, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.input_detec_class.setFont(font)
        self.input_detec_class.setStyleSheet("border:none;\n"
"border-bottom: 3px solid rgba(255, 0, 0, 200); \n"
"background-color:qradialgradient(stop:1 rgba(255, 255, 255, 0));\n"
"color:rgb(255, 255, 255);\n"
"")
        self.input_detec_class.setObjectName("input_detec_class")
        self.btn_detec_start = QtWidgets.QPushButton(self.display_detec)
        self.btn_detec_start.setGeometry(QtCore.QRect(20, 430, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.btn_detec_start.setFont(font)
        self.btn_detec_start.setStyleSheet("QPushButton#btn_detec_start{\n"
"border-radius: 20px;\n"
"background-color: rgba(255, 0, 0, 200);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#btn_detec_start:hover{\n"
"border-radius: 20px;\n"
"background-color: rgba(255, 0, 0, 150);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.btn_detec_start.setIcon(icon)
        self.btn_detec_start.setIconSize(QtCore.QSize(25, 25))
        self.btn_detec_start.setObjectName("btn_detec_start")
        self.btn_detec_close = QtWidgets.QPushButton(self.display_detec)
        self.btn_detec_close.setGeometry(QtCore.QRect(690, 490, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.btn_detec_close.setFont(font)
        self.btn_detec_close.setStyleSheet("QPushButton#btn_detec_close{\n"
"border-radius: 20px;\n"
"background-color: rgb(83, 249, 0);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#btn_detec_close:hover{\n"
"border-radius: 20px;\n"
"background-color: rgb(83, 249, 0,150);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.btn_detec_close.setIcon(icon2)
        self.btn_detec_close.setObjectName("btn_detec_close")
        self.btn_detec_export = QtWidgets.QPushButton(self.display_detec)
        self.btn_detec_export.setGeometry(QtCore.QRect(540, 380, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.btn_detec_export.setFont(font)
        self.btn_detec_export.setStyleSheet("QPushButton#btn_detec_export{\n"
"border-radius: 20px;\n"
"background-color: rgb(255, 85, 0);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#btn_detec_export:hover{\n"
"border-radius: 20px;\n"
"background-color: rgb(255, 85, 0,150);\n"
"color: rgb(255, 255, 255);\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Image/sace_rm.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_detec_export.setIcon(icon3)
        self.btn_detec_export.setIconSize(QtCore.QSize(20, 30))
        self.btn_detec_export.setObjectName("btn_detec_export")
        self.label_5 = QtWidgets.QLabel(self.display_detec)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 71, 61))
        self.label_5.setStyleSheet("background-color:qradialgradient(stop:1 rgba(255, 255, 255, 0));")
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("Image/logo_hk_rm.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.display_detec)
        self.label_7.setGeometry(QtCore.QRect(460, 80, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 0, 0);\n"
"background-color:qradialgradient(stop:1 rgba(255, 255, 255, 0));")
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(self.display_detec)
        self.label_9.setGeometry(QtCore.QRect(460, 110, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(255, 0, 0);\n"
"background-color:qradialgradient(stop:1 rgba(255, 255, 255, 0));")
        self.label_9.setObjectName("label_9")
        self.btn_detec_menu = QtWidgets.QPushButton(self.display_detec)
        self.btn_detec_menu.setGeometry(QtCore.QRect(10, 490, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.btn_detec_menu.setFont(font)
        self.btn_detec_menu.setStyleSheet("QPushButton#btn_detec_menu{\n"
"border-radius: 20px;\n"
"background-color: rgb(209, 209, 0);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#btn_detec_menu:hover{\n"
"border-radius: 20px;\n"
"background-color: rgb(209, 209, 0,150);\n"
"color: rgb(255, 255, 255);\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Image/home_rm.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_detec_menu.setIcon(icon4)
        self.btn_detec_menu.setIconSize(QtCore.QSize(20, 20))
        self.btn_detec_menu.setObjectName("btn_detec_menu")
        self.btn_detec_kt_thong_tin = QtWidgets.QPushButton(self.display_detec)
        self.btn_detec_kt_thong_tin.setGeometry(QtCore.QRect(260, 430, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.btn_detec_kt_thong_tin.setFont(font)
        self.btn_detec_kt_thong_tin.setStyleSheet("QPushButton#btn_detec_kt_thong_tin{\n"
"border-radius: 20px;\n"
"background-color: rgb(34, 163, 159,200);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#btn_detec_kt_thong_tin:hover{\n"
"border-radius: 20px;\n"
"background-color: rgb(34, 163, 159,150);\n"
"color: rgb(255, 255, 255);\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Image/trich_xuat_rm_font.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_detec_kt_thong_tin.setIcon(icon5)
        self.btn_detec_kt_thong_tin.setIconSize(QtCore.QSize(20, 30))
        self.btn_detec_kt_thong_tin.setObjectName("btn_detec_kt_thong_tin")
        self.btn_detec_bot_telegram = QtWidgets.QPushButton(self.display_detec)
        self.btn_detec_bot_telegram.setGeometry(QtCore.QRect(540, 490, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.btn_detec_bot_telegram.setFont(font)
        self.btn_detec_bot_telegram.setStyleSheet("QPushButton#btn_detec_bot_telegram{\n"
"border-radius: 20px;\n"
"background-color: rgb(255, 85, 127);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#btn_detec_bot_telegram:hover{\n"
"border-radius: 20px;\n"
"background-color: rgb(255, 85, 127,150);\n"
"color: rgb(255, 255, 255);\n"
"}")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("Image/bot_rm.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_detec_bot_telegram.setIcon(icon6)
        self.btn_detec_bot_telegram.setIconSize(QtCore.QSize(30, 30))
        self.btn_detec_bot_telegram.setObjectName("btn_detec_bot_telegram")
        self.main_widget.addWidget(self.display_detec)
        self.display_attendace = QtWidgets.QWidget()
        self.display_attendace.setObjectName("display_attendace")
        self.btn_attendance_camera = QtWidgets.QLabel(self.display_attendace)
        self.btn_attendance_camera.setGeometry(QtCore.QRect(20, 90, 381, 381))
        self.btn_attendance_camera.setStyleSheet("background-color:rgb(34, 34, 34);")
        self.btn_attendance_camera.setFrameShape(QtWidgets.QFrame.Box)
        self.btn_attendance_camera.setText("")
        self.btn_attendance_camera.setObjectName("btn_attendance_camera")
        self.btn_attendance_qr_detect_return = QtWidgets.QPushButton(self.display_attendace)
        self.btn_attendance_qr_detect_return.setGeometry(QtCore.QRect(20, 480, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_attendance_qr_detect_return.setFont(font)
        self.btn_attendance_qr_detect_return.setStyleSheet("QPushButton#btn_attendance_qr_detect_return{\n"
"border-radius: 20px;\n"
"background-color: rgb(203, 203, 0);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#btn_attendance_qr_detect_return:hover{\n"
"border-radius: 20px;\n"
"background-color: rgb(203, 203, 0,150);\n"
"color: rgb(255, 255, 255);\n"
"}")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("Image/tro_ve_rm.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_attendance_qr_detect_return.setIcon(icon7)
        self.btn_attendance_qr_detect_return.setObjectName("btn_attendance_qr_detect_return")
        self.btn_attendance_qr_detect_close = QtWidgets.QPushButton(self.display_attendace)
        self.btn_attendance_qr_detect_close.setGeometry(QtCore.QRect(290, 480, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_attendance_qr_detect_close.setFont(font)
        self.btn_attendance_qr_detect_close.setStyleSheet("QPushButton#btn_attendance_qr_detect_close{\n"
"border-radius: 20px;\n"
"background-color: rgb(84, 180, 53,200);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#btn_attendance_qr_detect_close:hover{\n"
"border-radius: 20px;\n"
"background-color: rgb(84, 180, 53,150);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.btn_attendance_qr_detect_close.setIcon(icon2)
        self.btn_attendance_qr_detect_close.setObjectName("btn_attendance_qr_detect_close")
        self.input_attendance_name = QtWidgets.QLineEdit(self.display_attendace)
        self.input_attendance_name.setGeometry(QtCore.QRect(420, 140, 331, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.input_attendance_name.setFont(font)
        self.input_attendance_name.setStyleSheet("border:none;\n"
"border-bottom: 3px solid rgba(255, 0, 0, 200); \n"
"background-color:qradialgradient(stop:1 rgba(255, 255, 255, 0));\n"
"color: rgb(255, 255, 255);\n"
"\n"
"")
        self.input_attendance_name.setObjectName("input_attendance_name")
        self.input_attendance_sdb_2 = QtWidgets.QLineEdit(self.display_attendace)
        self.input_attendance_sdb_2.setGeometry(QtCore.QRect(420, 200, 331, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.input_attendance_sdb_2.setFont(font)
        self.input_attendance_sdb_2.setStyleSheet("border:none;\n"
"border-bottom: 3px solid rgba(255, 0, 0, 200); \n"
"background-color:qradialgradient(stop:1 rgba(255, 255, 255, 0));\n"
"color: rgb(255, 255, 255);\n"
"")
        self.input_attendance_sdb_2.setObjectName("input_attendance_sdb_2")
        self.input_attendance_school = QtWidgets.QLineEdit(self.display_attendace)
        self.input_attendance_school.setGeometry(QtCore.QRect(420, 260, 331, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.input_attendance_school.setFont(font)
        self.input_attendance_school.setStyleSheet("border:none;\n"
"border-bottom: 3px solid rgba(255, 0, 0, 200); \n"
"background-color:qradialgradient(stop:1 rgba(255, 255, 255, 0));\n"
"color: rgb(255, 255, 255);\n"
"\n"
"")
        self.input_attendance_school.setObjectName("input_attendance_school")
        self.input_attendance_class = QtWidgets.QLineEdit(self.display_attendace)
        self.input_attendance_class.setGeometry(QtCore.QRect(420, 320, 331, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.input_attendance_class.setFont(font)
        self.input_attendance_class.setStyleSheet("border:none;\n"
"border-bottom: 3px solid rgba(255, 0, 0, 200); \n"
"background-color:qradialgradient(stop:1 rgba(255, 255, 255, 0));\n"
"color: rgb(255, 255, 255);\n"
"\n"
"")
        self.input_attendance_class.setObjectName("input_attendance_class")
        self.label_8 = QtWidgets.QLabel(self.display_attendace)
        self.label_8.setGeometry(QtCore.QRect(90, 10, 661, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color:rgb(255, 255, 255);\n"
"background-color:qradialgradient(stop:1 rgba(255, 255, 255, 0));")
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("Image/Diem_danh_bang_ma_qr.png"))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.btn_attendance_checked = QtWidgets.QPushButton(self.display_attendace)
        self.btn_attendance_checked.setGeometry(QtCore.QRect(530, 400, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.btn_attendance_checked.setFont(font)
        self.btn_attendance_checked.setStyleSheet("QPushButton#btn_attendance_checked{\n"
"border-radius: 20px;\n"
"background-color: rgba(255, 0, 0, 200);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#btn_attendance_checked:hover{\n"
"border-radius: 20px;\n"
"background-color: rgba(255, 0, 0, 150);\n"
"color: rgb(255, 255, 255);\n"
"}")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("Image/ma_qr_xoa_phong.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_attendance_checked.setIcon(icon8)
        self.btn_attendance_checked.setIconSize(QtCore.QSize(20, 20))
        self.btn_attendance_checked.setObjectName("btn_attendance_checked")
        self.main_widget.addWidget(self.display_attendace)
        self.display_data = QtWidgets.QWidget()
        self.display_data.setObjectName("display_data")
        self.data_title = QtWidgets.QLabel(self.display_data)
        self.data_title.setGeometry(QtCore.QRect(150, 10, 541, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.data_title.setFont(font)
        self.data_title.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:qradialgradient(stop:1 rgba(255, 255, 255, 0));")
        self.data_title.setText("")
        self.data_title.setPixmap(QtGui.QPixmap("Image/Tao_ma_qr.png"))
        self.data_title.setAlignment(QtCore.Qt.AlignCenter)
        self.data_title.setObjectName("data_title")
        self.btn_attendance_qr_return = QtWidgets.QPushButton(self.display_data)
        self.btn_attendance_qr_return.setGeometry(QtCore.QRect(10, 480, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_attendance_qr_return.setFont(font)
        self.btn_attendance_qr_return.setStyleSheet("QPushButton#btn_attendance_qr_return{\n"
"border-radius: 20px;\n"
"background-color: rgb(208, 208, 0);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#btn_attendance_qr_return:hover{\n"
"border-radius: 20px;\n"
"background-color:rgb(208, 208, 0,150);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.btn_attendance_qr_return.setIcon(icon7)
        self.btn_attendance_qr_return.setObjectName("btn_attendance_qr_return")
        self.btn_attendance_qr_close = QtWidgets.QPushButton(self.display_data)
        self.btn_attendance_qr_close.setGeometry(QtCore.QRect(680, 480, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_attendance_qr_close.setFont(font)
        self.btn_attendance_qr_close.setStyleSheet("QPushButton#btn_attendance_qr_close{\n"
"border-radius: 20px;\n"
"background-color:rgb(84, 180, 53,200);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#btn_attendance_qr_close:hover{\n"
"border-radius: 20px;\n"
"background-color: rgb(84, 180, 53,150);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.btn_attendance_qr_close.setIcon(icon2)
        self.btn_attendance_qr_close.setObjectName("btn_attendance_qr_close")
        self.input_data_name = QtWidgets.QLineEdit(self.display_data)
        self.input_data_name.setGeometry(QtCore.QRect(160, 120, 481, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.input_data_name.setFont(font)
        self.input_data_name.setStyleSheet("border:none;\n"
"border-bottom: 3px solid rgba(255, 0, 0, 200); \n"
"background-color:qradialgradient(stop:1 rgba(255, 255, 255, 0));\n"
"color: rgb(255, 255, 255);\n"
"\n"
"")
        self.input_data_name.setObjectName("input_data_name")
        self.input_data_sbd = QtWidgets.QLineEdit(self.display_data)
        self.input_data_sbd.setGeometry(QtCore.QRect(160, 190, 481, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.input_data_sbd.setFont(font)
        self.input_data_sbd.setStyleSheet("border:none;\n"
"border-bottom: 3px solid rgba(255, 0, 0, 200); \n"
"background-color:qradialgradient(stop:1 rgba(255, 255, 255, 0));\n"
"color: rgb(255, 255, 255);\n"
"\n"
"")
        self.input_data_sbd.setObjectName("input_data_sbd")
        self.input_data_school = QtWidgets.QLineEdit(self.display_data)
        self.input_data_school.setGeometry(QtCore.QRect(160, 260, 481, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.input_data_school.setFont(font)
        self.input_data_school.setStyleSheet("border:none;\n"
"color: rgb(255, 255, 255);\n"
"border-bottom: 3px solid rgba(255, 0, 0, 200); \n"
"background-color:qradialgradient(stop:1 rgba(255, 255, 255, 0));\n"
"\n"
"")
        self.input_data_school.setObjectName("input_data_school")
        self.input_data_class = QtWidgets.QLineEdit(self.display_data)
        self.input_data_class.setGeometry(QtCore.QRect(160, 330, 481, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.input_data_class.setFont(font)
        self.input_data_class.setStyleSheet("border:none;\n"
"color: rgb(255, 255, 255);\n"
"border-bottom: 3px solid rgba(255, 0, 0, 200); \n"
"background-color:qradialgradient(stop:1 rgba(255, 255, 255, 0));\n"
"\n"
"")
        self.input_data_class.setObjectName("input_data_class")
        self.btn_data_save = QtWidgets.QPushButton(self.display_data)
        self.btn_data_save.setGeometry(QtCore.QRect(330, 380, 171, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_data_save.setFont(font)
        self.btn_data_save.setStyleSheet("QPushButton#btn_data_save{\n"
"border-radius: 20px;\n"
"background-color: rgba(255, 0, 0, 200);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#btn_data_save:hover{\n"
"border-radius: 20px;\n"
"background-color: rgba(255, 0, 0, 150);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.btn_data_save.setIcon(icon3)
        self.btn_data_save.setObjectName("btn_data_save")
        self.btn_detec_bot_telegram_qr = QtWidgets.QPushButton(self.display_data)
        self.btn_detec_bot_telegram_qr.setGeometry(QtCore.QRect(530, 480, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.btn_detec_bot_telegram_qr.setFont(font)
        self.btn_detec_bot_telegram_qr.setStyleSheet("QPushButton#btn_detec_bot_telegram_qr{\n"
"border-radius: 20px;\n"
"background-color: rgb(255, 85, 127);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#btn_detec_bot_telegram_qr:hover{\n"
"border-radius: 20px;\n"
"background-color: rgb(255, 85, 127,150);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.btn_detec_bot_telegram_qr.setIcon(icon6)
        self.btn_detec_bot_telegram_qr.setIconSize(QtCore.QSize(30, 30))
        self.btn_detec_bot_telegram_qr.setObjectName("btn_detec_bot_telegram_qr")
        self.main_widget.addWidget(self.display_data)
        self.display_tuluan = QtWidgets.QWidget()
        self.display_tuluan.setObjectName("display_tuluan")
        self.label_2 = QtWidgets.QLabel(self.display_tuluan)
        self.label_2.setGeometry(QtCore.QRect(230, -10, 421, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: white;\n"
"background-color:qradialgradient(stop:1 rgba(255, 255, 255, 0));\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.input_screen_image = QtWidgets.QLabel(self.display_tuluan)
        self.input_screen_image.setGeometry(QtCore.QRect(20, 80, 341, 301))
        self.input_screen_image.setStyleSheet("background-color:rgb(34, 34, 34);")
        self.input_screen_image.setFrameShape(QtWidgets.QFrame.Box)
        self.input_screen_image.setText("")
        self.input_screen_image.setObjectName("input_screen_image")
        self.input_answer = QtWidgets.QLineEdit(self.display_tuluan)
        self.input_answer.setGeometry(QtCore.QRect(370, 110, 351, 31))
        self.input_answer.setStyleSheet("background-color: qradialgradient(stop:1 rgba(255, 255, 255, 0));\n"
"border: none;\n"
"border-bottom: 3px solid rgb(225, 225, 225);\n"
"color: white;")
        self.input_answer.setObjectName("input_answer")
        self.input_test = QtWidgets.QLineEdit(self.display_tuluan)
        self.input_test.setGeometry(QtCore.QRect(370, 180, 351, 31))
        self.input_test.setStyleSheet("background-color: qradialgradient(stop:1 rgba(255, 255, 255, 0));\n"
"border: none;\n"
"border-bottom: 3px solid rgb(225, 225, 225);\n"
"color: white;")
        self.input_test.setObjectName("input_test")
        self.btn_input_answer = QtWidgets.QPushButton(self.display_tuluan)
        self.btn_input_answer.setGeometry(QtCore.QRect(730, 112, 81, 31))
        self.btn_input_answer.setStyleSheet("QPushButton#btn_input_answer{\n"
"border-radius: 5px;\n"
"background-color: rgba(255, 0, 0, 200);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#btn_input_answer:hover{\n"
"border-radius: 5px;\n"
"background-color: rgba(255, 0, 0, 150);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.btn_input_answer.setObjectName("btn_input_answer")
        self.btn_input_test = QtWidgets.QPushButton(self.display_tuluan)
        self.btn_input_test.setGeometry(QtCore.QRect(730, 182, 81, 31))
        self.btn_input_test.setStyleSheet("QPushButton#btn_input_test{\n"
"border-radius: 5px;\n"
"background-color: rgba(255, 0, 0, 200);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#btn_input_test:hover{\n"
"border-radius: 5px;\n"
"background-color: rgba(255, 0, 0, 150);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.btn_input_test.setObjectName("btn_input_test")
        self.btn_tl_menu = QtWidgets.QPushButton(self.display_tuluan)
        self.btn_tl_menu.setGeometry(QtCore.QRect(10, 480, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.btn_tl_menu.setFont(font)
        self.btn_tl_menu.setStyleSheet("QPushButton#btn_tl_menu{\n"
"border-radius: 20px;\n"
"background-color: rgba(255, 0, 0, 200);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#btn_tl_menu:hover{\n"
"border-radius: 20px;\n"
"background-color: rgba(255, 0, 0, 150);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.btn_tl_menu.setIcon(icon4)
        self.btn_tl_menu.setObjectName("btn_tl_menu")
        self.btn_tl_close = QtWidgets.QPushButton(self.display_tuluan)
        self.btn_tl_close.setGeometry(QtCore.QRect(680, 480, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.btn_tl_close.setFont(font)
        self.btn_tl_close.setStyleSheet("QPushButton#btn_tl_close{\n"
"border-radius: 20px;\n"
"background-color: rgb(77, 232, 0);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#btn_tl_close:hover{\n"
"border-radius: 20px;\n"
"background-color: rgb(77, 232, 0,150);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.btn_tl_close.setObjectName("btn_tl_close")
        self.btn_tl_kiemtra = QtWidgets.QPushButton(self.display_tuluan)
        self.btn_tl_kiemtra.setGeometry(QtCore.QRect(390, 300, 181, 81))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.btn_tl_kiemtra.setFont(font)
        self.btn_tl_kiemtra.setStyleSheet("QPushButton#btn_tl_kiemtra{\n"
"border-radius: 20px;\n"
"background-color: rgb(170, 85, 127);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#btn_tl_kiemtra:hover{\n"
"border-radius: 20px;\n"
"background-color: rgb(170, 85, 127,150);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.btn_tl_kiemtra.setObjectName("btn_tl_kiemtra")
        self.btn_show_answer_folder = QtWidgets.QPushButton(self.display_tuluan)
        self.btn_show_answer_folder.setGeometry(QtCore.QRect(610, 300, 171, 81))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.btn_show_answer_folder.setFont(font)
        self.btn_show_answer_folder.setStyleSheet("QPushButton#btn_show_answer_folder{\n"
"border-radius: 20px;\n"
"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#btn_show_answer_folder:hover{\n"
"border-radius: 20px;\n"
"background-color: rgb(0, 170, 255,150);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.btn_show_answer_folder.setObjectName("btn_show_answer_folder")
        self.main_widget.addWidget(self.display_tuluan)
        self.display_attendance_menu = QtWidgets.QWidget()
        self.display_attendance_menu.setObjectName("display_attendance_menu")
        self.label_3 = QtWidgets.QLabel(self.display_attendance_menu)
        self.label_3.setGeometry(QtCore.QRect(250, 10, 371, 71))
        font = QtGui.QFont()
        font.setPointSize(29)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:rgb(255, 255, 255);\n"
"background-color: qradialgradient(stop:1 rgba(255, 255, 255, 0))")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("Image/Diem_danh.png"))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.btn_menu_attendance_qr = QtWidgets.QPushButton(self.display_attendance_menu)
        self.btn_menu_attendance_qr.setGeometry(QtCore.QRect(180, 160, 501, 81))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.btn_menu_attendance_qr.setFont(font)
        self.btn_menu_attendance_qr.setStyleSheet("QPushButton#btn_menu_attendance_qr{\n"
"border-radius: 15px;\n"
"background-color: rgb(3, 201, 136,200);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#btn_menu_attendance_qr:hover{\n"
"border-radius: 15px;\n"
"background-color: rgb(3, 201, 136,150);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.btn_menu_attendance_qr.setIcon(icon8)
        self.btn_menu_attendance_qr.setIconSize(QtCore.QSize(60, 60))
        self.btn_menu_attendance_qr.setObjectName("btn_menu_attendance_qr")
        self.btn_menu_attendance_face = QtWidgets.QPushButton(self.display_attendance_menu)
        self.btn_menu_attendance_face.setGeometry(QtCore.QRect(180, 280, 501, 81))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.btn_menu_attendance_face.setFont(font)
        self.btn_menu_attendance_face.setStyleSheet("QPushButton#btn_menu_attendance_face{\n"
"border-radius: 15px;\n"
"background-color: rgb(255, 150, 0);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#btn_menu_attendance_face:hover{\n"
"border-radius: 15px;\n"
"background-color:  rgb(255, 150, 0,150);\n"
"color: rgb(255, 255, 255);\n"
"}")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("Image/khuon_mat_xoa_phong.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_menu_attendance_face.setIcon(icon9)
        self.btn_menu_attendance_face.setIconSize(QtCore.QSize(60, 60))
        self.btn_menu_attendance_face.setObjectName("btn_menu_attendance_face")
        self.btn_menu_attendance_return = QtWidgets.QPushButton(self.display_attendance_menu)
        self.btn_menu_attendance_return.setGeometry(QtCore.QRect(10, 480, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.btn_menu_attendance_return.setFont(font)
        self.btn_menu_attendance_return.setStyleSheet("QPushButton#btn_menu_attendance_return{\n"
"border-radius: 15px;\n"
"background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#btn_menu_attendance_return:hover{\n"
"border-radius: 15px;\n"
"background-color: rgb(255, 0, 0,150);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.btn_menu_attendance_return.setIcon(icon7)
        self.btn_menu_attendance_return.setObjectName("btn_menu_attendance_return")
        self.btn_menu_attendance_close = QtWidgets.QPushButton(self.display_attendance_menu)
        self.btn_menu_attendance_close.setGeometry(QtCore.QRect(670, 480, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.btn_menu_attendance_close.setFont(font)
        self.btn_menu_attendance_close.setStyleSheet("QPushButton#btn_menu_attendance_close{\n"
"border-radius: 15px;\n"
"background-color: rgb(0, 200, 0);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#btn_menu_attendance_close:hover{\n"
"border-radius: 15px;\n"
"background-color: rgb(0, 200, 0,150);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.btn_menu_attendance_close.setIcon(icon2)
        self.btn_menu_attendance_close.setObjectName("btn_menu_attendance_close")
        self.main_widget.addWidget(self.display_attendance_menu)
        self.display_attendance_qr_code = QtWidgets.QWidget()
        self.display_attendance_qr_code.setObjectName("display_attendance_qr_code")
        self.btn_attendance_make_qr_data = QtWidgets.QPushButton(self.display_attendance_qr_code)
        self.btn_attendance_make_qr_data.setGeometry(QtCore.QRect(190, 110, 471, 91))
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.btn_attendance_make_qr_data.setFont(font)
        self.btn_attendance_make_qr_data.setStyleSheet("QPushButton#btn_attendance_make_qr_data{\n"
"border-radius: 15px;\n"
"background-color: rgb(3, 201, 136,200);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#btn_attendance_make_qr_data:hover{\n"
"border-radius: 15px;\n"
"background-color: rgb(3, 201, 136,150);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.btn_attendance_make_qr_data.setIcon(icon8)
        self.btn_attendance_make_qr_data.setIconSize(QtCore.QSize(60, 60))
        self.btn_attendance_make_qr_data.setObjectName("btn_attendance_make_qr_data")
        self.btn_attendance_as_qr_code = QtWidgets.QPushButton(self.display_attendance_qr_code)
        self.btn_attendance_as_qr_code.setGeometry(QtCore.QRect(190, 220, 471, 91))
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.btn_attendance_as_qr_code.setFont(font)
        self.btn_attendance_as_qr_code.setStyleSheet("QPushButton#btn_attendance_as_qr_code{\n"
"border-radius: 15px;\n"
"background-color: rgb(3, 150, 136,200);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#btn_attendance_as_qr_code:hover{\n"
"border-radius: 15px;\n"
"background-color: rgb(3, 150, 136,150);\n"
"color: rgb(255, 255, 255);\n"
"}")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("Image/may_quet_xoa_phong.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_attendance_as_qr_code.setIcon(icon10)
        self.btn_attendance_as_qr_code.setIconSize(QtCore.QSize(60, 60))
        self.btn_attendance_as_qr_code.setObjectName("btn_attendance_as_qr_code")
        self.btn_attendance_show_list_qr = QtWidgets.QPushButton(self.display_attendance_qr_code)
        self.btn_attendance_show_list_qr.setGeometry(QtCore.QRect(190, 330, 471, 91))
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.btn_attendance_show_list_qr.setFont(font)
        self.btn_attendance_show_list_qr.setStyleSheet("QPushButton#btn_attendance_show_list_qr{\n"
"border-radius: 15px;\n"
"background-color: rgb(170, 85, 255);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#btn_attendance_show_list_qr:hover{\n"
"border-radius: 15px;\n"
"background-color:rgb(170, 85, 255,150);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.btn_attendance_show_list_qr.setIcon(icon1)
        self.btn_attendance_show_list_qr.setIconSize(QtCore.QSize(60, 60))
        self.btn_attendance_show_list_qr.setObjectName("btn_attendance_show_list_qr")
        self.btn_menu_attendance_qr_return = QtWidgets.QPushButton(self.display_attendance_qr_code)
        self.btn_menu_attendance_qr_return.setGeometry(QtCore.QRect(10, 480, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.btn_menu_attendance_qr_return.setFont(font)
        self.btn_menu_attendance_qr_return.setStyleSheet("QPushButton#btn_menu_attendance_qr_return{\n"
"border-radius: 15px;\n"
"background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#btn_menu_attendance_qr_return:hover{\n"
"border-radius: 15px;\n"
"background-color: rgb(255, 0, 0,150);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.btn_menu_attendance_qr_return.setIcon(icon7)
        self.btn_menu_attendance_qr_return.setObjectName("btn_menu_attendance_qr_return")
        self.btn_menu_attendance_qr_close = QtWidgets.QPushButton(self.display_attendance_qr_code)
        self.btn_menu_attendance_qr_close.setGeometry(QtCore.QRect(670, 480, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.btn_menu_attendance_qr_close.setFont(font)
        self.btn_menu_attendance_qr_close.setStyleSheet("QPushButton#btn_menu_attendance_qr_close{\n"
"border-radius: 15px;\n"
"background-color: rgb(0, 200, 0);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#btn_menu_attendance_qr_close:hover{\n"
"border-radius: 15px;\n"
"background-color: rgb(0, 200, 0,150);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.btn_menu_attendance_qr_close.setIcon(icon2)
        self.btn_menu_attendance_qr_close.setIconSize(QtCore.QSize(20, 20))
        self.btn_menu_attendance_qr_close.setObjectName("btn_menu_attendance_qr_close")
        self.label_4 = QtWidgets.QLabel(self.display_attendance_qr_code)
        self.label_4.setGeometry(QtCore.QRect(90, 20, 691, 51))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("Image/Diem_danh_bang_ma_qr.png"))
        self.label_4.setObjectName("label_4")
        self.main_widget.addWidget(self.display_attendance_qr_code)
        self.display_attendance_face = QtWidgets.QWidget()
        self.display_attendance_face.setObjectName("display_attendance_face")
        self.label_10 = QtWidgets.QLabel(self.display_attendance_face)
        self.label_10.setGeometry(QtCore.QRect(70, 0, 691, 81))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color:rgb(255, 255, 255);\n"
"background-color: qradialgradient(stop:1 rgba(255, 255, 255, 0))")
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("Image/Diem_danh_khuon_mat.png"))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.btn_attendance_make_face_data = QtWidgets.QPushButton(self.display_attendance_face)
        self.btn_attendance_make_face_data.setGeometry(QtCore.QRect(200, 90, 441, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btn_attendance_make_face_data.setFont(font)
        self.btn_attendance_make_face_data.setStyleSheet("QPushButton#btn_attendance_make_face_data{\n"
"border-radius: 15px;\n"
"background-color: rgb(3, 201, 136,200);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#btn_attendance_make_face_data:hover{\n"
"border-radius: 15px;\n"
"background-color: rgb(3, 201, 136,150);\n"
"color: rgb(255, 255, 255);\n"
"}")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("Image/tao_du_lieu_xoa_phong.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_attendance_make_face_data.setIcon(icon11)
        self.btn_attendance_make_face_data.setIconSize(QtCore.QSize(60, 60))
        self.btn_attendance_make_face_data.setObjectName("btn_attendance_make_face_data")
        self.btn_attendance_update_data = QtWidgets.QPushButton(self.display_attendance_face)
        self.btn_attendance_update_data.setGeometry(QtCore.QRect(200, 190, 441, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btn_attendance_update_data.setFont(font)
        self.btn_attendance_update_data.setStyleSheet("QPushButton#btn_attendance_update_data{\n"
"border-radius: 15px;\n"
"background-color: rgb(85, 85, 255,200);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#btn_attendance_update_data:hover{\n"
"border-radius: 15px;\n"
"background-color: rgb(85, 85, 255,150);\n"
"color: rgb(255, 255, 255);\n"
"}")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("Image/cap_nhat_xoa_phong.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_attendance_update_data.setIcon(icon12)
        self.btn_attendance_update_data.setIconSize(QtCore.QSize(50, 50))
        self.btn_attendance_update_data.setObjectName("btn_attendance_update_data")
        self.btn_attendance_as_face = QtWidgets.QPushButton(self.display_attendance_face)
        self.btn_attendance_as_face.setGeometry(QtCore.QRect(200, 290, 441, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btn_attendance_as_face.setFont(font)
        self.btn_attendance_as_face.setStyleSheet("QPushButton#btn_attendance_as_face{\n"
"border-radius: 15px;\n"
"background-color: rgb(177, 177, 0);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#btn_attendance_as_face:hover{\n"
"border-radius: 15px;\n"
"background-color: rgb(177, 177, 0,150);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.btn_attendance_as_face.setIcon(icon9)
        self.btn_attendance_as_face.setIconSize(QtCore.QSize(60, 60))
        self.btn_attendance_as_face.setObjectName("btn_attendance_as_face")
        self.btn_attendance_show_list_face = QtWidgets.QPushButton(self.display_attendance_face)
        self.btn_attendance_show_list_face.setGeometry(QtCore.QRect(200, 390, 441, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btn_attendance_show_list_face.setFont(font)
        self.btn_attendance_show_list_face.setStyleSheet("QPushButton#btn_attendance_show_list_face{\n"
"border-radius: 15px;\n"
"background-color: rgb(255, 85, 127);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#btn_attendance_show_list_face:hover{\n"
"border-radius: 15px;\n"
"background-color:rgb(255, 85, 127,150);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.btn_attendance_show_list_face.setIcon(icon1)
        self.btn_attendance_show_list_face.setIconSize(QtCore.QSize(60, 60))
        self.btn_attendance_show_list_face.setObjectName("btn_attendance_show_list_face")
        self.btn_menu_attendance_face_return = QtWidgets.QPushButton(self.display_attendance_face)
        self.btn_menu_attendance_face_return.setGeometry(QtCore.QRect(10, 480, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.btn_menu_attendance_face_return.setFont(font)
        self.btn_menu_attendance_face_return.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_menu_attendance_face_return.setStyleSheet("QPushButton#btn_menu_attendance_face_return{\n"
"border-radius: 15px;\n"
"background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#btn_menu_attendance_face_return:hover{\n"
"border-radius: 15px;\n"
"background-color: rgb(255, 0, 0,150);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.btn_menu_attendance_face_return.setIcon(icon7)
        self.btn_menu_attendance_face_return.setObjectName("btn_menu_attendance_face_return")
        self.btn_menu_attendance_face_close = QtWidgets.QPushButton(self.display_attendance_face)
        self.btn_menu_attendance_face_close.setGeometry(QtCore.QRect(700, 480, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.btn_menu_attendance_face_close.setFont(font)
        self.btn_menu_attendance_face_close.setStyleSheet("QPushButton#btn_menu_attendance_face_close{\n"
"border-radius: 15px;\n"
"background-color: rgb(0, 200, 0);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#btn_menu_attendance_face_close:hover{\n"
"border-radius: 15px;\n"
"background-color: rgb(0, 200, 0,150);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.btn_menu_attendance_face_close.setIcon(icon2)
        self.btn_menu_attendance_face_close.setObjectName("btn_menu_attendance_face_close")
        self.main_widget.addWidget(self.display_attendance_face)
        self.display_attendance_make_data_face = QtWidgets.QWidget()
        self.display_attendance_make_data_face.setObjectName("display_attendance_make_data_face")
        self.label_11 = QtWidgets.QLabel(self.display_attendance_make_data_face)
        self.label_11.setGeometry(QtCore.QRect(110, 10, 621, 61))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color:rgb(255, 255, 255);\n"
"background-color: qradialgradient(stop:1 rgba(255, 255, 255, 0))")
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("Image/Tao_du_lieu_khuon_mat.png"))
        self.label_11.setObjectName("label_11")
        self.input_camera_make_data = QtWidgets.QLabel(self.display_attendance_make_data_face)
        self.input_camera_make_data.setGeometry(QtCore.QRect(20, 80, 241, 321))
        self.input_camera_make_data.setStyleSheet("background-color: rgb(67, 66, 66);")
        self.input_camera_make_data.setFrameShape(QtWidgets.QFrame.Box)
        self.input_camera_make_data.setText("")
        self.input_camera_make_data.setObjectName("input_camera_make_data")
        self.input_data_cam = QtWidgets.QLineEdit(self.display_attendance_make_data_face)
        self.input_data_cam.setGeometry(QtCore.QRect(270, 80, 411, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_data_cam.setFont(font)
        self.input_data_cam.setStyleSheet("border:none;\n"
"border-bottom: 3px solid rgba(255, 0, 0, 200); \n"
"background-color:qradialgradient(stop:1 rgba(255, 255, 255, 0));\n"
"color: rgb(255, 255, 255);\n"
"\n"
"")
        self.input_data_cam.setObjectName("input_data_cam")
        self.btn_data_input = QtWidgets.QPushButton(self.display_attendance_make_data_face)
        self.btn_data_input.setGeometry(QtCore.QRect(700, 82, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_data_input.setFont(font)
        self.btn_data_input.setStyleSheet("QPushButton#btn_data_input{\n"
"border-radius: 20px;\n"
"background-color: rgb(255, 85, 0);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#btn_data_input:hover{\n"
"border-radius: 20px;\n"
"background-color: rgb(255, 85, 0,150);\n"
"color: rgb(255, 255, 255);\n"
"}")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("Image/dau_tick_xanh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_data_input.setIcon(icon13)
        self.btn_data_input.setObjectName("btn_data_input")
        self.input_id_face = QtWidgets.QLineEdit(self.display_attendance_make_data_face)
        self.input_id_face.setGeometry(QtCore.QRect(270, 150, 411, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.input_id_face.setFont(font)
        self.input_id_face.setStyleSheet("border:none;\n"
"border-bottom: 3px solid rgba(255, 0, 0, 200); \n"
"background-color:qradialgradient(stop:1 rgba(255, 255, 255, 0));\n"
"color: rgb(255, 255, 255);\n"
"\n"
"")
        self.input_id_face.setObjectName("input_id_face")
        self.input_name_face = QtWidgets.QLineEdit(self.display_attendance_make_data_face)
        self.input_name_face.setGeometry(QtCore.QRect(270, 210, 411, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.input_name_face.setFont(font)
        self.input_name_face.setStyleSheet("border:none;\n"
"border-bottom: 3px solid rgba(255, 0, 0, 200); \n"
"background-color:qradialgradient(stop:1 rgba(255, 255, 255, 0));\n"
"color: rgb(255, 255, 255);\n"
"\n"
"")
        self.input_name_face.setObjectName("input_name_face")
        self.input_class_face = QtWidgets.QLineEdit(self.display_attendance_make_data_face)
        self.input_class_face.setGeometry(QtCore.QRect(270, 270, 411, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.input_class_face.setFont(font)
        self.input_class_face.setStyleSheet("border:none;\n"
"border-bottom: 3px solid rgba(255, 0, 0, 200); \n"
"background-color:qradialgradient(stop:1 rgba(255, 255, 255, 0));\n"
"color: rgb(255, 255, 255);\n"
"\n"
"")
        self.input_class_face.setObjectName("input_class_face")
        self.input_school_face = QtWidgets.QLineEdit(self.display_attendance_make_data_face)
        self.input_school_face.setGeometry(QtCore.QRect(270, 330, 411, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.input_school_face.setFont(font)
        self.input_school_face.setStyleSheet("border:none;\n"
"border-bottom: 3px solid rgba(255, 0, 0, 200); \n"
"background-color:qradialgradient(stop:1 rgba(255, 255, 255, 0));\n"
"color: rgb(255, 255, 255);\n"
"\n"
"")
        self.input_school_face.setObjectName("input_school_face")
        self.btn_make_face_data = QtWidgets.QPushButton(self.display_attendance_make_data_face)
        self.btn_make_face_data.setGeometry(QtCore.QRect(290, 380, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_make_face_data.setFont(font)
        self.btn_make_face_data.setStyleSheet("QPushButton#btn_make_face_data{\n"
"border-radius: 20px;\n"
"background-color: rgb(170, 85, 0);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#btn_make_face_data:hover{\n"
"border-radius: 20px;\n"
"background-color:rgb(170, 85, 0,150);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.btn_make_face_data.setIcon(icon11)
        self.btn_make_face_data.setIconSize(QtCore.QSize(20, 20))
        self.btn_make_face_data.setObjectName("btn_make_face_data")
        self.btn_export_face_data = QtWidgets.QPushButton(self.display_attendance_make_data_face)
        self.btn_export_face_data.setGeometry(QtCore.QRect(520, 380, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_export_face_data.setFont(font)
        self.btn_export_face_data.setStyleSheet("QPushButton#btn_export_face_data{\n"
"border-radius: 20px;\n"
"background-color: rgb(81, 163, 244);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#btn_export_face_data:hover{\n"
"border-radius: 20px;\n"
"background-color:  rgb(81, 163, 244,150);\n"
"color: rgb(255, 255, 255);\n"
"}")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("Image/tx_xoa_phong.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_export_face_data.setIcon(icon14)
        self.btn_export_face_data.setIconSize(QtCore.QSize(15, 30))
        self.btn_export_face_data.setObjectName("btn_export_face_data")
        self.btn_make_data_face_menu = QtWidgets.QPushButton(self.display_attendance_make_data_face)
        self.btn_make_data_face_menu.setGeometry(QtCore.QRect(10, 490, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_make_data_face_menu.setFont(font)
        self.btn_make_data_face_menu.setStyleSheet("QPushButton#btn_make_data_face_menu{\n"
"border-radius: 20px;\n"
"background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#btn_make_data_face_menu:hover{\n"
"border-radius: 20px;\n"
"background-color: rgb(255, 0, 0,150);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.btn_make_data_face_menu.setIcon(icon7)
        self.btn_make_data_face_menu.setObjectName("btn_make_data_face_menu")
        self.btn_make_data_face_close = QtWidgets.QPushButton(self.display_attendance_make_data_face)
        self.btn_make_data_face_close.setGeometry(QtCore.QRect(670, 490, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_make_data_face_close.setFont(font)
        self.btn_make_data_face_close.setStyleSheet("QPushButton#btn_make_data_face_close{\n"
"border-radius: 20px;\n"
"background-color:rgb(85, 170, 0);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#btn_make_data_face_close:hover{\n"
"border-radius: 20px;\n"
"background-color:  rgb(85, 170, 0,150);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.btn_make_data_face_close.setIcon(icon2)
        self.btn_make_data_face_close.setObjectName("btn_make_data_face_close")
        self.btn_show_folder_face = QtWidgets.QPushButton(self.display_attendance_make_data_face)
        self.btn_show_folder_face.setGeometry(QtCore.QRect(180, 490, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_show_folder_face.setFont(font)
        self.btn_show_folder_face.setStyleSheet("QPushButton#btn_show_folder_face{\n"
"border-radius: 20px;\n"
"background-color: rgb(0, 170, 127);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#btn_show_folder_face:hover{\n"
"border-radius: 20px;\n"
"background-color: rgb(0, 170, 127,150);\n"
"color: rgb(255, 255, 255);\n"
"}")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("Image/folder_RM.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_show_folder_face.setIcon(icon15)
        self.btn_show_folder_face.setIconSize(QtCore.QSize(20, 20))
        self.btn_show_folder_face.setObjectName("btn_show_folder_face")
        self.main_widget.addWidget(self.display_attendance_make_data_face)
        self.diplay_attendance_update_data_face = QtWidgets.QWidget()
        self.diplay_attendance_update_data_face.setObjectName("diplay_attendance_update_data_face")
        self.label_13 = QtWidgets.QLabel(self.diplay_attendance_update_data_face)
        self.label_13.setGeometry(QtCore.QRect(170, 10, 531, 71))
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color:rgb(255, 255, 255);\n"
"background-color: qradialgradient(stop:1 rgba(255, 255, 255, 0))")
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("Image/Cap_nhat_du_lieu.png"))
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.time_data_update = QtWidgets.QLabel(self.diplay_attendance_update_data_face)
        self.time_data_update.setGeometry(QtCore.QRect(20, 120, 681, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.time_data_update.setFont(font)
        self.time_data_update.setStyleSheet("color:rgb(255, 255, 255);\n"
"background-color: qradialgradient(stop:1 rgba(255, 255, 255, 0))")
        self.time_data_update.setObjectName("time_data_update")
        self.btn_update_data = QtWidgets.QPushButton(self.diplay_attendance_update_data_face)
        self.btn_update_data.setGeometry(QtCore.QRect(240, 190, 411, 91))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btn_update_data.setFont(font)
        self.btn_update_data.setStyleSheet("QPushButton#btn_update_data{\n"
"border-radius: 20px;\n"
"background-color: rgb(255, 85, 0);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#btn_update_data:hover{\n"
"border-radius: 20px;\n"
"background-color:rgb(85, 170, 0,150);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.btn_update_data.setIcon(icon11)
        self.btn_update_data.setIconSize(QtCore.QSize(60, 60))
        self.btn_update_data.setObjectName("btn_update_data")
        self.label_tinh_trang = QtWidgets.QLabel(self.diplay_attendance_update_data_face)
        self.label_tinh_trang.setGeometry(QtCore.QRect(260, 300, 371, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_tinh_trang.setFont(font)
        self.label_tinh_trang.setStyleSheet("color:rgb(255, 0 , 0);\n"
"background-color: qradialgradient(stop:1 rgba(255, 255, 255, 0))")
        self.label_tinh_trang.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tinh_trang.setObjectName("label_tinh_trang")
        self.btn_attendance_update_data_return = QtWidgets.QPushButton(self.diplay_attendance_update_data_face)
        self.btn_attendance_update_data_return.setGeometry(QtCore.QRect(10, 480, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.btn_attendance_update_data_return.setFont(font)
        self.btn_attendance_update_data_return.setStyleSheet("QPushButton#btn_attendance_update_data_return{\n"
"border-radius: 20px;\n"
"background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#btn_attendance_update_data_return:hover{\n"
"border-radius: 20px;\n"
"background-color: rgb(255, 0, 0,150);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.btn_attendance_update_data_return.setIcon(icon7)
        self.btn_attendance_update_data_return.setObjectName("btn_attendance_update_data_return")
        self.btn_attendance_update_data_close = QtWidgets.QPushButton(self.diplay_attendance_update_data_face)
        self.btn_attendance_update_data_close.setGeometry(QtCore.QRect(660, 480, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.btn_attendance_update_data_close.setFont(font)
        self.btn_attendance_update_data_close.setStyleSheet("QPushButton#btn_attendance_update_data_close{\n"
"border-radius: 20px;\n"
"background-color: rgb(85, 170, 0);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#btn_attendance_update_data_close:hover{\n"
"border-radius: 20px;\n"
"background-color:  rgb(85, 170, 0,150);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.btn_attendance_update_data_close.setIcon(icon2)
        self.btn_attendance_update_data_close.setObjectName("btn_attendance_update_data_close")
        self.btn_show_data_model = QtWidgets.QPushButton(self.diplay_attendance_update_data_face)
        self.btn_show_data_model.setGeometry(QtCore.QRect(330, 400, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.btn_show_data_model.setFont(font)
        self.btn_show_data_model.setStyleSheet("QPushButton#btn_show_data_model{\n"
"border-radius: 20px;\n"
"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#btn_show_data_model:hover{\n"
"border-radius: 20px;\n"
"background-color:  rgb(0, 170, 255,150);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.btn_show_data_model.setIcon(icon15)
        self.btn_show_data_model.setObjectName("btn_show_data_model")
        self.main_widget.addWidget(self.diplay_attendance_update_data_face)
        self.display_attendance_face_detect = QtWidgets.QWidget()
        self.display_attendance_face_detect.setObjectName("display_attendance_face_detect")
        self.input_camera_attendance_face = QtWidgets.QLabel(self.display_attendance_face_detect)
        self.input_camera_attendance_face.setGeometry(QtCore.QRect(10, 90, 251, 311))
        self.input_camera_attendance_face.setStyleSheet("background-color: rgb(67, 66, 66);")
        self.input_camera_attendance_face.setFrameShape(QtWidgets.QFrame.Box)
        self.input_camera_attendance_face.setText("")
        self.input_camera_attendance_face.setObjectName("input_camera_attendance_face")
        self.input_attendance_face_cam = QtWidgets.QLineEdit(self.display_attendance_face_detect)
        self.input_attendance_face_cam.setGeometry(QtCore.QRect(270, 90, 411, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_attendance_face_cam.setFont(font)
        self.input_attendance_face_cam.setStyleSheet("border:none;\n"
"border-bottom: 3px solid rgba(255, 0, 0, 200); \n"
"background-color:qradialgradient(stop:1 rgba(255, 255, 255, 0));\n"
"color: rgb(255, 255, 255);\n"
"\n"
"")
        self.input_attendance_face_cam.setObjectName("input_attendance_face_cam")
        self.btn_attendance_face_cam = QtWidgets.QPushButton(self.display_attendance_face_detect)
        self.btn_attendance_face_cam.setGeometry(QtCore.QRect(700, 90, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_attendance_face_cam.setFont(font)
        self.btn_attendance_face_cam.setStyleSheet("QPushButton#btn_attendance_face_cam{\n"
"border-radius: 20px;\n"
"background-color: rgb(255, 85, 0);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#btn_attendance_face_cam:hover{\n"
"border-radius: 20px;\n"
"background-color: rgb(255, 85, 0,150);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.btn_attendance_face_cam.setIcon(icon13)
        self.btn_attendance_face_cam.setObjectName("btn_attendance_face_cam")
        self.input_attendance_face_name = QtWidgets.QLineEdit(self.display_attendance_face_detect)
        self.input_attendance_face_name.setGeometry(QtCore.QRect(270, 150, 411, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.input_attendance_face_name.setFont(font)
        self.input_attendance_face_name.setStyleSheet("border:none;\n"
"border-bottom: 3px solid rgba(255, 0, 0, 200); \n"
"background-color:qradialgradient(stop:1 rgba(255, 255, 255, 0));\n"
"color: rgb(255, 255, 255);\n"
"\n"
"")
        self.input_attendance_face_name.setObjectName("input_attendance_face_name")
        self.input_attendance_face_class = QtWidgets.QLineEdit(self.display_attendance_face_detect)
        self.input_attendance_face_class.setGeometry(QtCore.QRect(270, 210, 411, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.input_attendance_face_class.setFont(font)
        self.input_attendance_face_class.setStyleSheet("border:none;\n"
"border-bottom: 3px solid rgba(255, 0, 0, 200); \n"
"background-color:qradialgradient(stop:1 rgba(255, 255, 255, 0));\n"
"color: rgb(255, 255, 255);\n"
"\n"
"")
        self.input_attendance_face_class.setObjectName("input_attendance_face_class")
        self.input_attendance_face_school = QtWidgets.QLineEdit(self.display_attendance_face_detect)
        self.input_attendance_face_school.setGeometry(QtCore.QRect(270, 270, 411, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.input_attendance_face_school.setFont(font)
        self.input_attendance_face_school.setStyleSheet("border:none;\n"
"border-bottom: 3px solid rgba(255, 0, 0, 200); \n"
"background-color:qradialgradient(stop:1 rgba(255, 255, 255, 0));\n"
"color: rgb(255, 255, 255);\n"
"\n"
"")
        self.input_attendance_face_school.setObjectName("input_attendance_face_school")
        self.btn_attendance_face_diemdanh = QtWidgets.QPushButton(self.display_attendance_face_detect)
        self.btn_attendance_face_diemdanh.setGeometry(QtCore.QRect(300, 340, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_attendance_face_diemdanh.setFont(font)
        self.btn_attendance_face_diemdanh.setStyleSheet("QPushButton#btn_attendance_face_diemdanh{\n"
"border-radius: 20px;\n"
"background-color: rgb(85, 170, 255);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#btn_attendance_face_diemdanh:hover{\n"
"border-radius: 20px;\n"
"background-color: rgb(85, 170, 255,150);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.btn_attendance_face_diemdanh.setIcon(icon9)
        self.btn_attendance_face_diemdanh.setIconSize(QtCore.QSize(20, 20))
        self.btn_attendance_face_diemdanh.setObjectName("btn_attendance_face_diemdanh")
        self.btn_xacnhan_face = QtWidgets.QPushButton(self.display_attendance_face_detect)
        self.btn_xacnhan_face.setGeometry(QtCore.QRect(530, 340, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_xacnhan_face.setFont(font)
        self.btn_xacnhan_face.setStyleSheet("QPushButton#btn_xacnhan_face{\n"
"border-radius: 20px;\n"
"background-color:rgb(85, 85, 127);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#btn_xacnhan_face:hover{\n"
"border-radius: 20px;\n"
"background-color:rgb(85, 85, 127,150);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.btn_xacnhan_face.setIcon(icon13)
        self.btn_xacnhan_face.setObjectName("btn_xacnhan_face")
        self.label_15 = QtWidgets.QLabel(self.display_attendance_face_detect)
        self.label_15.setGeometry(QtCore.QRect(70, 10, 711, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color:rgb(255, 255, 255);\n"
"background-color: qradialgradient(stop:1 rgba(255, 255, 255, 0))")
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap("Image/Diem_danh_khuon_mat.png"))
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.btn_attendance_face_return = QtWidgets.QPushButton(self.display_attendance_face_detect)
        self.btn_attendance_face_return.setGeometry(QtCore.QRect(10, 490, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_attendance_face_return.setFont(font)
        self.btn_attendance_face_return.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_attendance_face_return.setStyleSheet("QPushButton#btn_attendance_face_return{\n"
"border-radius: 20px;\n"
"background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#btn_attendance_face_return:hover{\n"
"border-radius: 20px;\n"
"background-color: rgb(255, 0, 0,150);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.btn_attendance_face_return.setIcon(icon7)
        self.btn_attendance_face_return.setObjectName("btn_attendance_face_return")
        self.btn_attendance_face_close = QtWidgets.QPushButton(self.display_attendance_face_detect)
        self.btn_attendance_face_close.setGeometry(QtCore.QRect(660, 490, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_attendance_face_close.setFont(font)
        self.btn_attendance_face_close.setStyleSheet("QPushButton#btn_attendance_face_close{\n"
"border-radius: 20px;\n"
"background-color:rgb(0, 170, 0);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#btn_attendance_face_close:hover{\n"
"border-radius: 20px;\n"
"background-color: rgb(0, 170, 0,150);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.btn_attendance_face_close.setIcon(icon2)
        self.btn_attendance_face_close.setIconSize(QtCore.QSize(20, 20))
        self.btn_attendance_face_close.setObjectName("btn_attendance_face_close")
        self.main_widget.addWidget(self.display_attendance_face_detect)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 821, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.main_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_menu_detec.setText(_translate("MainWindow", "Giám sát"))
        self.btn_menu_attendance.setText(_translate("MainWindow", "Điểm danh"))
        self.btn_menu_close.setText(_translate("MainWindow", "Thoát"))
        self.input_detec_name.setPlaceholderText(_translate("MainWindow", "Mời nhập họ và tên"))
        self.input_detec_sbd.setPlaceholderText(_translate("MainWindow", "Mời nhập số báo danh"))
        self.input_detec_school.setPlaceholderText(_translate("MainWindow", "Mời nhập tên trường"))
        self.input_detec_class.setPlaceholderText(_translate("MainWindow", "Mời nhập phòng thi"))
        self.btn_detec_start.setText(_translate("MainWindow", "Bắt đầu"))
        self.btn_detec_close.setText(_translate("MainWindow", "Thoát"))
        self.btn_detec_export.setText(_translate("MainWindow", "Lưu"))
        self.label_7.setText(_translate("MainWindow", "Lưu ý: Điền đầy đủ thông tin"))
        self.label_9.setText(_translate("MainWindow", "Click vào Lưu sau khi điền xong"))
        self.btn_detec_menu.setText(_translate("MainWindow", "Trang chủ"))
        self.btn_detec_kt_thong_tin.setText(_translate("MainWindow", "Trích xuất"))
        self.btn_detec_bot_telegram.setText(_translate("MainWindow", "BOT Mail"))
        self.btn_attendance_qr_detect_return.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>QPushButton#btn_attendance_menu{</p><p>border-radius: 20px;</p><p>background-color: rgba(255, 0, 0, 200);</p><p>color: rgb(255, 255, 255);</p><p>}</p><p><br/></p><p>QPushButton#btn_attendance_menu:hover{</p><p>border-radius: 20px;</p><p>background-color: rgba(255, 0, 0, 150);</p><p>color: rgb(255, 255, 255);</p><p>}</p></body></html>"))
        self.btn_attendance_qr_detect_return.setText(_translate("MainWindow", "Trở về"))
        self.btn_attendance_qr_detect_close.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>QPushButton#btn_attendance_menu{</p><p>border-radius: 20px;</p><p>background-color: rgba(255, 0, 0, 200);</p><p>color: rgb(255, 255, 255);</p><p>}</p><p><br/></p><p>QPushButton#btn_attendance_menu:hover{</p><p>border-radius: 20px;</p><p>background-color: rgba(255, 0, 0, 150);</p><p>color: rgb(255, 255, 255);</p><p>}</p></body></html>"))
        self.btn_attendance_qr_detect_close.setText(_translate("MainWindow", "Thoát"))
        self.input_attendance_name.setPlaceholderText(_translate("MainWindow", "Tên học sinh"))
        self.input_attendance_sdb_2.setPlaceholderText(_translate("MainWindow", "Số báo danh"))
        self.input_attendance_school.setPlaceholderText(_translate("MainWindow", "Tên trường"))
        self.input_attendance_class.setPlaceholderText(_translate("MainWindow", "Tên lớp"))
        self.btn_attendance_checked.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>QPushButton#btn_attendance_menu{</p><p>border-radius: 20px;</p><p>background-color: rgba(255, 0, 0, 200);</p><p>color: rgb(255, 255, 255);</p><p>}</p><p><br/></p><p>QPushButton#btn_attendance_menu:hover{</p><p>border-radius: 20px;</p><p>background-color: rgba(255, 0, 0, 150);</p><p>color: rgb(255, 255, 255);</p><p>}</p></body></html>"))
        self.btn_attendance_checked.setText(_translate("MainWindow", "Mã QR"))
        self.btn_attendance_qr_return.setText(_translate("MainWindow", "Trở về"))
        self.btn_attendance_qr_close.setText(_translate("MainWindow", "Thoát"))
        self.input_data_name.setPlaceholderText(_translate("MainWindow", "Mời nhập tên"))
        self.input_data_sbd.setPlaceholderText(_translate("MainWindow", "Mời nhập số báo danh"))
        self.input_data_school.setPlaceholderText(_translate("MainWindow", "Mời nhập tên trường"))
        self.input_data_class.setPlaceholderText(_translate("MainWindow", "Mời nhập tên lớp"))
        self.btn_data_save.setText(_translate("MainWindow", "Lưu mã QR"))
        self.btn_detec_bot_telegram_qr.setText(_translate("MainWindow", "BOT QR"))
        self.label_2.setText(_translate("MainWindow", "Kiểm tra câu trả lời sai"))
        self.btn_input_answer.setText(_translate("MainWindow", "Chọn"))
        self.btn_input_test.setText(_translate("MainWindow", "Chọn"))
        self.btn_tl_menu.setText(_translate("MainWindow", "Trang chủ"))
        self.btn_tl_close.setText(_translate("MainWindow", "Thoát"))
        self.btn_tl_kiemtra.setText(_translate("MainWindow", "Kiểm tra"))
        self.btn_show_answer_folder.setText(_translate("MainWindow", "Xem kết quả"))
        self.btn_menu_attendance_qr.setText(_translate("MainWindow", "Điểm danh bằng mã QR"))
        self.btn_menu_attendance_face.setText(_translate("MainWindow", "Điểm danh bằng khuôn mặt"))
        self.btn_menu_attendance_return.setText(_translate("MainWindow", "Trở về"))
        self.btn_menu_attendance_close.setText(_translate("MainWindow", "Thoát"))
        self.btn_attendance_make_qr_data.setText(_translate("MainWindow", "Tạo mã QR"))
        self.btn_attendance_as_qr_code.setText(_translate("MainWindow", "Điểm danh"))
        self.btn_attendance_show_list_qr.setText(_translate("MainWindow", "Xem danh sách"))
        self.btn_menu_attendance_qr_return.setText(_translate("MainWindow", "Trở về"))
        self.btn_menu_attendance_qr_close.setText(_translate("MainWindow", "Thoát"))
        self.btn_attendance_make_face_data.setText(_translate("MainWindow", "Tạo dữ liệu khuôn mặt"))
        self.btn_attendance_update_data.setText(_translate("MainWindow", "Cập nhật dữ liệu"))
        self.btn_attendance_as_face.setText(_translate("MainWindow", "Điểm danh"))
        self.btn_attendance_show_list_face.setText(_translate("MainWindow", "Xem danh sách"))
        self.btn_menu_attendance_face_return.setText(_translate("MainWindow", "Trở về"))
        self.btn_menu_attendance_face_close.setText(_translate("MainWindow", "Thoát"))
        self.input_data_cam.setPlaceholderText(_translate("MainWindow", "Nguồn dữ liệu"))
        self.btn_data_input.setText(_translate("MainWindow", "Chọn"))
        self.input_id_face.setPlaceholderText(_translate("MainWindow", "Mã học sinh"))
        self.input_name_face.setPlaceholderText(_translate("MainWindow", "Tên học sinh"))
        self.input_class_face.setPlaceholderText(_translate("MainWindow", "Tên lớp"))
        self.input_school_face.setPlaceholderText(_translate("MainWindow", "Tên trường"))
        self.btn_make_face_data.setText(_translate("MainWindow", "Tạo dữ liệu"))
        self.btn_export_face_data.setText(_translate("MainWindow", "Trích xuất dữ liệu"))
        self.btn_make_data_face_menu.setText(_translate("MainWindow", "Trở về"))
        self.btn_make_data_face_close.setText(_translate("MainWindow", "Thoát"))
        self.btn_show_folder_face.setText(_translate("MainWindow", "Thư mục ảnh"))
        self.time_data_update.setText(_translate("MainWindow", "Lần cập nhật gần nhất vào ngày: "))
        self.btn_update_data.setText(_translate("MainWindow", "Cập nhật dữ liệu"))
        self.label_tinh_trang.setText(_translate("MainWindow", "Tình trạng: Chưa cập nhật"))
        self.btn_attendance_update_data_return.setText(_translate("MainWindow", "Trở về"))
        self.btn_attendance_update_data_close.setText(_translate("MainWindow", "Thoát"))
        self.btn_show_data_model.setText(_translate("MainWindow", "Kiểm tra dữ liệu"))
        self.input_attendance_face_cam.setPlaceholderText(_translate("MainWindow", "Nguồn dữ liệu"))
        self.btn_attendance_face_cam.setText(_translate("MainWindow", "Chọn"))
        self.input_attendance_face_name.setPlaceholderText(_translate("MainWindow", "Tên học sinh"))
        self.input_attendance_face_class.setPlaceholderText(_translate("MainWindow", "Tên lớp"))
        self.input_attendance_face_school.setPlaceholderText(_translate("MainWindow", "Tên trường"))
        self.btn_attendance_face_diemdanh.setText(_translate("MainWindow", "Điểm danh"))
        self.btn_xacnhan_face.setText(_translate("MainWindow", "Xác nhận"))
        self.btn_attendance_face_return.setText(_translate("MainWindow", "  Trở về"))
        self.btn_attendance_face_close.setText(_translate("MainWindow", "Thoát"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
